version: 2.1
jobs:
  build:
    working_directory: ~/rendora
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: make build
      - setup_remote_docker
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t ${DOCKER_REPO}:${CIRCLE_SHA1} .
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              docker push ${DOCKER_REPO}:${CIRCLE_SHA1}
            fi